project:
  type: website

website:
  title: "ISSS608-VAA-Project Group 7"
  navbar:
    left: 
      - text: User Guide
        href: "user_guide.qmd"
      - href: "Project-Proposal/VAA-Project-Proposal_Group7.qmd"
        text: Proposal
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

