project:
  type: website

website:
  title: "ISSS608-VAA-Project Group 7"
  navbar:
<<<<<<< HEAD
    left: 
      - text: User Guide
        href: user_guide.qmd
  
=======
    left:
      - href: "Project-Proposal/VAA-Project-Proposal_Group7.html"
        text: Proposal
>>>>>>> 706db1e98b7a9ffda7778a1853bdf25132644646
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

