project:
  type: website

website:
  title: "Water is life"
  navbar:
    background: primary
    right:
      - href: overview.qmd
        text: Overview
      - href: user_guide.qmd
        text: User Guide 
      - href: https://rkyaw.shinyapps.io/waterislife/
        text: Shiny App 
      - href: poster.qmd
        text: Poster
      - about.qmd

format:
  html:
    theme: 
      - cosmo
      - custom.css
    css: styles.css
    toc: false

editor: visual

