project:
  type: website

website:
  title: "ISSS608-VAA-Project Group 7"
  navbar:

    left: 
      - href: Project-Proposal/Proposal.qmd
        text: Proposal
      - href: user_guide.qmd
        text: User Guide
        


        
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

