project:
  type: website

website:
  title: "Water is life"
  navbar:
        
    right:
      - href: overview.qmd
        text: Overview
      - href: user_guide.qmd
        text: User Guide 
      - href: shiny_app.qmd
        text: Shiny App 
      - href: poster.qmd
        text: Poster
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

