project:
  type: website

website:
  title: "ISSS608-VAA-Project Group 7"
  navbar:
    left:
      - href: "Project-Proposal/VAA-Project-Proposal_Group7.html"
        text: Proposal
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

