---
title: "test"
---

```{r}
pacman::p_load(sf, spdep, tmap, tidyverse, patchwork,funModeling)
```

```{r}
wpdx <- read_csv("data\\aspatial\\WPdx_NGAv1.2.1.csv", show_col_types = FALSE)

```

```{r}
nigeria <- st_read(dsn = "data\\geospatial",
                   layer = "geoBoundaries-NGA-ADM2")
```

```{r}
nigeria <- nigeria %>% 
    rename(`LGA` = `shapeName`)
```

```{r}
nigeria$LGA[94] <- "Bassa_Kogi"
nigeria$LGA[95] <- "Bassa_Plateau"
nigeria$LGA[304] <- "Ifelodun, Kwara"
nigeria$LGA[305] <- "Ifelodun, Osun"
nigeria$LGA[355] <- "Irepodun, Kwara"
nigeria$LGA[356] <- "Irepodun, Osun"
nigeria$LGA[519] <- "Nassarawa, Kano"
nigeria$LGA[546] <- "Obi, Benue"
nigeria$LGA[547] <- "Obi, Nasarawa"
nigeria$LGA[693] <- "Surulere, Lagos"
nigeria$LGA[694] <- "Surulere, Oyo"
```

```{r}
nigeria$LGA[duplicated(nigeria$LGA)==TRUE]
```

```{r}
count(wpdx, `#status_clean`)
```

```{r}
wpdx_nigeria_clean <- wpdx %>%
  mutate(`#status_clean` = recode(`#status_clean`, "Non functional due to dry season" = "Non-Functional due to dry season")) %>%
  mutate(`#status_clean` = replace_na(`#status_clean`, "Unknown")) %>%
  mutate(`#water_tech_category` = replace_na(`#water_tech_category`, "Unknown")) %>%
  mutate(`#water_source_category` = replace_na(`#water_source_category`, "Unknown")) %>%
  mutate(`#water_source_category` = replace_na(`#water_source_category`, "Unknown"))

wpdx_nigeria_clean <- wpdx_nigeria_clean %>%
  mutate(`Water_Source` = `#water_source_category`) %>%
  mutate(`Water_Tech` = `#water_tech_category`) %>%
  mutate(`Functional_Status` = `#status_clean`) %>%
  mutate(`Functional_Status` = recode(`Functional_Status`,
        "Abandoned" = "Non-Functional",
        "Abandoned/Decommissioned" = "Non-Functional",
        "Functional but needs repair" = "Functional",
        "Functional but not in use" = "Functional",
        "Non-Functional due to dry season" = "Non-Functional"))

count(wpdx_nigeria_clean, `Functional_Status`)
    
```

```{r}
count(wpdx_nigeria_clean, `#water_source_category`)
```

```{r}
wpdx_nigeria_clean <- wpdx_nigeria_clean %>% 
    rename(`LGA` = `#clean_adm2`)
```

```{r}
wpdx_nigeria_sf <- st_as_sf(wpdx_nigeria_clean, 
                    coords = c("#lon_deg","#lat_deg"), 
                    crs=4326) 
```

```{r}
glimpse(wpdx_nigeria_sf)
```

```{r}
st_geometry(wpdx_nigeria_sf)
```

```{r}
functional <- wpdx_nigeria_sf %>%
  filter(`Functional_Status` == 'Functional')

non_functional <- wpdx_nigeria_sf %>%
  filter(`Functional_Status` == 'Non-Functional')

unknown <- wpdx_nigeria_sf %>%
  filter(`Functional_Status` == 'Unknown')

nigeria$wpt_functional <- lengths(st_intersects(nigeria, functional))
nigeria$wpt_nonfunctional <- lengths(st_intersects(nigeria, non_functional))
nigeria$wpt_unknown <-lengths(st_intersects(nigeria, unknown))
nigeria$wpt_total <- lengths(st_intersects(nigeria, functional)) + 
  lengths(st_intersects(nigeria, non_functional)) + 
  lengths(st_intersects(nigeria, unknown))
```

```{r}
freq(data = wpdx_nigeria_clean,
      input = 'Water_Tech')
```

```{r}
HandPump	 <- wpdx_nigeria_sf %>%
  filter(`Water_Tech` == 'Hand Pump')

MechanizedPump <- wpdx_nigeria_sf %>%
  filter(`Water_Tech` == 'Mechanized Pump')


nigeria$tech_HandPump <- lengths(st_intersects(nigeria, HandPump))
nigeria$tech_MechanizedPump <- lengths(st_intersects(nigeria, MechanizedPump))
```

```{r}
freq(data = wpdx_nigeria_clean,
      input = 'Water_Source')
```

```{r}
Spring <- wpdx_nigeria_sf %>%
  filter(`Water_Source` == 'Spring')

Well <- wpdx_nigeria_sf %>%
  filter(`Water_Source` == 'Well')

nigeria$source_Spring <- lengths(st_intersects(nigeria, Spring))
nigeria$source_Well <-lengths(st_intersects(nigeria, Well))
```

```{r}
nigeria <- nigeria %>%
  mutate(pct_functional = `wpt_functional`/ `wpt_total`) %>%
  mutate(`pct_functional` = replace_na(`pct_functional`, 0)) %>%
  mutate(pct_nonfunctional = `wpt_nonfunctional`/ `wpt_total`) %>%
  mutate(`pct_nonfunctional` = replace_na(`pct_nonfunctional`, 0))
```

```{r}
lowcap <- wpdx_nigeria_sf %>%
  filter(`usage_capacity` < 1000)

highcap <- wpdx_nigeria_sf %>%
  filter(`usage_capacity` >= 1000)

lowcrucial <- wpdx_nigeria_sf %>%
  filter(`crucialness_score` <= 0.30)

highcrucial <- wpdx_nigeria_sf %>%
  filter(`crucialness_score` > 0.30)

withinpressure <- wpdx_nigeria_sf %>%
  filter(`pressure_score` <= 1.183)

highpressure <- wpdx_nigeria_sf %>%
  filter(`pressure_score` > 1.183)

rural <- wpdx_nigeria_sf %>%
  filter(`is_urban` == 'FALSE')

urban <- wpdx_nigeria_sf %>%
  filter(`is_urban` == 'TRUE')
```

```{r}
nigeria$wpt_lowcap <- lengths(st_intersects(nigeria, lowcap))

nigeria$wpt_highcap <- lengths(st_intersects(nigeria, highcap))

nigeria$wpt_rural<- lengths(st_intersects(nigeria, rural))

nigeria$wpt_urban<- lengths(st_intersects(nigeria, urban))

nigeria$wpt_lowcrucial <- lengths(st_intersects(nigeria, lowcrucial))

nigeria$wpt_highcrucial <- lengths(st_intersects(nigeria, highcrucial))

nigeria$wpt_withinpressure <- lengths(st_intersects(nigeria, withinpressure))

nigeria$wpt_highpressure <- lengths(st_intersects(nigeria, highpressure))
```

```{r}
nigeria <- nigeria %>%
  
  mutate(`pct_spring` = `source_Spring`/`wpt_total`) %>%
  mutate(`pct_spring` = replace_na(`pct_spring`, 0)) %>%
  
  mutate(`pct_well` = `source_Well`/`wpt_total`) %>%
  mutate(`pct_well` = replace_na(`pct_well`, 0)) %>%
  
  mutate(`pct_handpump` = `tech_HandPump`/`wpt_total`) %>%
  mutate(`pct_handpump` = replace_na(`pct_handpump`, 0)) %>%
  
  mutate(`pct_mechpump` = `tech_MechanizedPump`/`wpt_total`) %>%
  mutate(`pct_mechpump` = replace_na(`pct_mechpump`, 0)) %>%
  
  mutate(`pct_lowcap` = `wpt_lowcap`/`wpt_total`) %>%
  mutate(`pct_lowcap` = replace_na(`pct_lowcap`, 0)) %>%
  
  mutate(`pct_highcap` = `wpt_highcap`/`wpt_total`) %>%
  mutate(`pct_highcap` = replace_na(`pct_highcap`, 0)) %>%
  
  mutate(`pct_rural` = `wpt_rural`/`wpt_total`) %>%
  mutate(`pct_rural` = replace_na(`pct_rural`, 0)) %>%
  
  mutate(`pct_urban` = `wpt_urban`/`wpt_total`) %>%
  mutate(`pct_urban` = replace_na(`pct_urban`, 0)) %>%
  
  mutate(`pct_lowcrucial` = `wpt_lowcrucial`/`wpt_total`) %>%
  mutate(`pct_lowcrucial` = replace_na(`pct_lowcrucial`, 0)) %>%
  
  mutate(`pct_highcrucial` = `wpt_highcrucial`/`wpt_total`) %>%
  mutate(`pct_highcrucial` = replace_na(`pct_highcrucial`, 0)) %>%
  
  mutate(`pct_withinpressure` = `wpt_withinpressure`/`wpt_total`) %>%
  mutate(`pct_withinpressure` = replace_na(`pct_withinpressure`, 0)) %>%

  mutate(`pct_highpressure` = `wpt_highpressure`/`wpt_total`) %>%
  mutate(`pct_highpressure` = replace_na(`pct_highpressure`, 0))
```

```{r}
nigeria <- nigeria %>%
  mutate(`pct_highpressure` = `wpt_highpressure`/`wpt_total`) %>%
  mutate(`pct_highpressure` = replace_na(`pct_highpressure`, 0))
```

```{r}
nigeria_gcs <- nigeria 
nigeria <- st_transform(nigeria, crs = 26391)
```

```{r}
st_geometry(nigeria)
```

```{r}
write_rds(nigeria, "data\\geodata\\wp_nga.rds")
```
